# Usa una imagen base de Node.js para construir la aplicación
FROM node:18 AS build

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos package.json y package-lock.json (si los tienes) al contenedor
COPY package*.json ./

# Instala las dependencias del frontend
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Expone el puerto por donde se servirá la app
EXPOSE 4000

# Define el comando para iniciar la aplicación
CMD ["npm", "start"]

